version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - machine:
          image: ubuntu-1604:201903-01
      - maven/test # checkout, build, test, and upload test results
